=== SmartBear/soapui/soapui-installer/src/dist/Tutorials/WSDL-WADL/NewsSearchResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--The contents of this file are subject to the terms
of the Common Development and Distribution License
(the "License").  You may not use this file except
in compliance with the License.

You can obtain a copy of the license at
http://www.opensource.org/licenses/cddl1.php
See the License for the specific language governing
permissions and limitations under the License.--><xs:schema targetNamespace="urn:yahoo:yn" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:yahoo:yn">
  <xs:element name="ResultSet">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Result" type="ResultType" minOccurs="0" maxOccurs="50"/>
      </xs:sequence>
      <xs:attribute name="totalResultsAvailable" type="xs:integer"/>
      <xs:attribute name="totalResultsReturned" type="xs:integer"/>
      <xs:attribute name="firstResultPosition" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="ResultType">
    <xs:sequence>
      <xs:element name="Title" type="xs:string"/>
      <xs:element name="Summary" type="xs:string"/>
      <xs:element name="Url" type="xs:string"/>
      <xs:element name="ClickUrl" type="xs:string"/>
      <xs:element name="NewsSource" type="xs:string"/>
      <xs:element name="NewsSourceUrl" type="xs:string"/>
      <xs:element name="Language" type="xs:string"/>
      <xs:element name="PublishDate" type="xs:string"/>
      <xs:element name="ModificationDate" type="xs:string" minOccurs="0"/>
      <xs:element name="Thumbnail" type="ImageType" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ImageType">
    <xs:sequence>
      <xs:element name="Url" type="xs:string"/>
      <xs:element name="Height" type="xs:integer" minOccurs="0"/>
      <xs:element name="Width" type="xs:integer" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema><!--ws02.search.re2.yahoo.com compressed/chunked Tue Oct 18 13:12:21 PDT 2005-->

=== SmartBear/soapui/soapui-installer/src/dist/Tutorials/restexample/NewsSearchService/V1/madonna_xml.xml
<ResultSet xsi:schemaLocation="urn:yahoo:yn http://api.search.yahoo.com/NewsSearchService/V1/NewsSearchResponse.xsd" totalResultsAvailable="2533" totalResultsReturned="10" firstResultPosition="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:yahoo:yn">
   <Result>
      <Title>Madonna appeals for girls school help</Title>
      <Summary>Madonna has taken a break from her world tour to ask fans to help her build a girls school in Malawi.</Summary>
      <Url>http://uk.news.yahoo.com/1/20081114/ten-madonna-appeals-for-girls-school-hel-c60bd6d.html</Url>
      <ClickUrl>http://uk.news.yahoo.com/1/20081114/ten-madonna-appeals-for-girls-school-hel-c60bd6d.html</ClickUrl>
      <NewsSource>world entertainment news via Yahoo! UK &amp; Ireland News</NewsSource>
      <NewsSourceUrl>http://uk.news.yahoo.com/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226647203</PublishDate>
      <ModificationDate>1226647267</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna hosts chili fundraiser on Nov. 22</Title>
      <Summary>Madonna Rehabilitation Hospital employees and friends will gather 6-9 p.m. Nov. 22 for the hospital’s fifth annual Chili and Soup Cookoff at Pius X High School, 6000 A St.</Summary>
      <Url>http://www.journalstar.com/articles/2008/11/13/news/local/doc491b51981a640009758823.txt</Url>
      <ClickUrl>http://www.journalstar.com/articles/2008/11/13/news/local/doc491b51981a640009758823.txt</ClickUrl>
      <NewsSource>Lincoln Journal Star</NewsSource>
      <NewsSourceUrl>http://www.journalstar.com/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226641524</PublishDate>
      <ModificationDate>1226641525</ModificationDate>
   </Result>
   <Result>
      <Title>Britney Spears erteilt Madonna eine Abfuhr</Title>
      <Summary>Los Angeles - Britney Spears hat einen gemeinsamen Auftritt mit Madonna abgesagt. Die 26-Jährige sollte eigentlich am 26. November in Miami mit der «Queen of Pop» auf der Bühne stehen.</Summary>
      <Url>http://www.nachrichten.ch/detail/324955.htm</Url>
      <ClickUrl>http://www.nachrichten.ch/detail/324955.htm</ClickUrl>
      <NewsSource>Nachrichten.ch</NewsSource>
      <NewsSourceUrl>http://www.nachrichten.ch/</NewsSourceUrl>
      <Language>de</Language>
      <PublishDate>1226650741</PublishDate>
      <ModificationDate>1226650742</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna quảng cáo cho Louis Vuitton</Title>
      <Summary>Diva Madonna sẽ là gương mặt quảng cáo cho chiến dịch xuân/hè 2009 của nhãn hiệu thời trang lừng danh thế giới Louis Vuitton.</Summary>
      <Url>http://tintuc.timnhanh.com/van_hoa/thoi_trang/20081114/35A8909B/</Url>
      <ClickUrl>http://tintuc.timnhanh.com/van_hoa/thoi_trang/20081114/35A8909B/</ClickUrl>
      <NewsSource>Tìm Nhanh!</NewsSource>
      <NewsSourceUrl>http://www.timnhanh.com/</NewsSourceUrl>
      <Language>vi</Language>
      <PublishDate>1226624055</PublishDate>
      <ModificationDate>1226624055</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna's 'gorgeous' A-Rod</Title>
      <Summary>Madonna has reportedly been gushing to close pals about rumoured lover Alex Rodriguez.</Summary>
      <Url>http://iafrica.com/entertain/news/1301740.htm</Url>
      <ClickUrl>http://iafrica.com/entertain/news/1301740.htm</ClickUrl>
      <NewsSource>iafrica.com</NewsSource>
      <NewsSourceUrl>http://iafrica.com/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226642536</PublishDate>
      <ModificationDate>1226642540</ModificationDate>
   </Result>
   <Result>
      <Title>'Madonna is smitten with Alex'</Title>
      <Summary>Pop star Madonna has reportedly been gushing to close pals about her rumoured lover Alex Rodriguez.</Summary>
      <Url>http://www.iol.co.za/widgets/rss_redirect.php?artid=4712682&amp;setid=0&amp;sectid=346&amp;url=tonight&amp;vne=1&amp;csect=Tonight</Url>
      <ClickUrl>http://www.iol.co.za/widgets/rss_redirect.php?artid=4712682&amp;setid=0&amp;sectid=346&amp;url=tonight&amp;vne=1&amp;csect=Tonight</ClickUrl>
      <NewsSource>Independent Online</NewsSource>
      <NewsSourceUrl>http://iol.co.za/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226653775</PublishDate>
      <ModificationDate>1226656531</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna - Madonna Appeals For Girls School Help</Title>
      <Summary>MADONNA has taken a break from her world tour to ask fans to help her build a girls school in Malawi. The pop superstar has filmed a brief video message about the ...</Summary>
      <Url>http://www.contactmusic.com/news.nsf/article/madonna%20appeals%20for%20girls%20school%20help_1086595</Url>
      <ClickUrl>http://www.contactmusic.com/news.nsf/article/madonna%20appeals%20for%20girls%20school%20help_1086595</ClickUrl>
      <NewsSource>ContactMusic</NewsSource>
      <NewsSourceUrl>http://www.contactmusic.com/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226628535</PublishDate>
      <ModificationDate>1226628536</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna to build girls school in Malawi, appeals for help</Title>
      <Summary>London, Nov 14 : Pop diva Madonna has taken a break from her world tour to concentrate on the girls school that she is building in Malawi.</Summary>
      <Url>http://www.newkerala.com/topstory-fullnews-45701.html</Url>
      <ClickUrl>http://www.newkerala.com/topstory-fullnews-45701.html</ClickUrl>
      <NewsSource>New Kerala</NewsSource>
      <NewsSourceUrl>http://www.newkerala.com/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226641437</PublishDate>
      <ModificationDate>1226641438</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna : ce que doit faire Guy Ritchie pour revoir ses enfants !</Title>
      <Summary>C'est la presse anglo saxonne qui sort aujourd'hui la liste des commandements que Madonna aurait imposés à Guy Ritchie depuis leur séparation, si ce dernier veut voir leurs enfants. Heureusement pour [... ]</Summary>
      <Url>http://fr.news.yahoo.com/45/20081113/ten-madonna-ce-que-doit-faire-guy-ritchi-a4307fe.html</Url>
      <ClickUrl>http://fr.news.yahoo.com/45/20081113/ten-madonna-ce-que-doit-faire-guy-ritchi-a4307fe.html</ClickUrl>
      <NewsSource>Dontmiss via Yahoo! Actualités</NewsSource>
      <NewsSourceUrl>http://fr.news.yahoo.com/</NewsSourceUrl>
      <Language>fr</Language>
      <PublishDate>1226601304</PublishDate>
      <ModificationDate>1226602116</ModificationDate>
   </Result>
   <Result>
      <Title>Madonna's 'gorgeous' A-Rod</Title>
      <Summary>Madonna says rumoured lover Alex Rodriguez "has the heart of a poet trapped inside an insanely gorgeous body."</Summary>
      <Url>http://www.chinadaily.com.cn/showbiz/2008-11/14/content_7205263.htm</Url>
      <ClickUrl>http://www.chinadaily.com.cn/showbiz/2008-11/14/content_7205263.htm</ClickUrl>
      <NewsSource>China Daily</NewsSource>
      <NewsSourceUrl>http://www.chinadaily.com.cn/</NewsSourceUrl>
      <Language>en</Language>
      <PublishDate>1226628504</PublishDate>
      <ModificationDate>1226628505</ModificationDate>
   </Result>
</ResultSet>
<!--ws06.search.re2.yahoo.com uncompressed/chunked Fri Nov 14 02:02:51 PST 2008-->
